name: Check store availability

# Controls when the action will run. 
on:
  schedule:
  - cron: "15 * * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  check_stock_availability:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Cleanup workspace path
      - name: Cleanup workspace path
        uses: mickem/clean-after-action@v1

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Checkout python
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        
      # Runs a set of commands using the runners shell
      - name: Install dependencies
        run: |
          pip install requests
          pip install tinydb
          pip install beautifulsoup4
          pip install pytablewriter
          pip install pytz
          pip install markdown
          pip install jsondiff
          pip install pytablewriter[html]
        
      # run the bike store availability check
      - name: Run script
        run: python ./main.py
      
      # commit the modified database to the main branch
      - name: Update files on GitHub
        uses: test-room-7/action-update-file@v1.5.0
        with:
          file-path: db/db.json
          commit-msg: updated database
          github-token: ${{ secrets.GITHUB_TOKEN }}

      # check if there is a change report file available 
      - name: Check if change report file exists
        id: bike_changes_available
        uses: andstor/file-existence-action@v1.0.1
        with:
          files: "report/bikes_changes_report.html"

      # List file names in report folder (asteric * is not supported in pandoc arguments - workaround)
      - name: Get file names for merge process
        id: files_list
        run: echo "::set-output name=report_names::$(printf '"%s" ' report/*.html)"

      # Convert using pandoc (https://github.com/pandoc/pandoc-action-example)
      - name: Merge HTML files
        uses: docker://pandoc/latex:2.11.2
        with:
          args:  "--standalone --output=report/merged_report.html ${{ steps.files_list.outputs.report_names }}"

      - name: Send email
        if: steps.check_stock_availability.outputs.bike_changes_available == 'true'
        uses: dawidd6/action-send-mail@v3.1.0
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: ROSEBIKES - Change
          from: ${{secrets.MAIL_USERNAME}}
          to: k.rohn@outlook.de
          secure: true
          html_body: file://report/merged_report.html
          #convert_markdown: true
          #attachments: report/bikes_available_report.md

      - name: upload reports
        uses: actions/upload-artifact@v2
        with:
          name: report
          path: report/*.html